# Generated by Django 4.1.4 on 2023-01-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happybackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallerydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(blank=True, max_length=50, null=True)),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('IMAGE', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.AlterField(
            model_name='adminregdb',
            name='IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
