# Generated by Django 4.1.4 on 2023-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happybackapp', '0002_gallerydb_alter_adminregdb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('PHOTOS', models.CharField(blank=True, max_length=50, null=True)),
                ('CAMERA', models.CharField(blank=True, max_length=50, null=True)),
                ('TERM', models.CharField(blank=True, max_length=50, null=True)),
                ('PRICING', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
