# Generated by Django 3.2.10 on 2023-02-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happybackapp', '0003_pricingdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingdb',
            name='IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
