# Generated by Django 3.2.10 on 2023-02-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happybackapp', '0004_pricingdb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingdb',
            name='IMAGE',
        ),
    ]
