# Generated by Django 3.2.10 on 2023-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happybackapp', '0005_remove_pricingdb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=50, null=True)),
                ('MOBILE', models.IntegerField(blank=True, null=True)),
                ('DATE', models.DateField(blank=True, max_length=50, null=True)),
                ('TYPE', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
