# Generated by Django 3.2.10 on 2023-02-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happybackapp', '0006_bookingdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=50, null=True)),
                ('SUBJECT', models.CharField(blank=True, max_length=50, null=True)),
                ('MESSAGE', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
