# Generated by Django 3.2.10 on 2023-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=50, null=True)),
                ('PASSWORD', models.IntegerField(blank=True, null=True)),
                ('CONFIRMPASSWORD', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
