# Generated by Django 3.2.10 on 2023-02-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindb',
            name='CONFIRMPASSWORD',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
